### ISSUE TITLE
[Bug] [Link Utilities] Co-Optimus absent from browser search submenu

### ISSUE THREAD

**Issue by psychopattt** [HerrKnarz/Playnite-Extensions#80]
**Description**
In Link Utilities, Co-Optimus is not showing up as an option in the "Open browser search on..." submenu

**To Reproduce**
1. Open the general settings for Link Utilities
2. Activate "Show in menu" for Co-Optimus
3. Right click on any game
4. Navigate to the "Open browser search on..." submenu
5. Co-Optimus is absent

**Expected behavior**
Co-Optimus should show up in the submenu like every other selected website

**Screenshots**
![1](https://github.com/HerrKnarz/Playnite-Extensions/assets/56837234/4b7e30b5-157c-45d0-90b8-a5f2fd252837)
![2](https://github.com/HerrKnarz/Playnite-Extensions/assets/56837234/6750112d-3e13-4b10-9746-68c9fc9b0715)
![3](https://github.com/HerrKnarz/Playnite-Extensions/assets/56837234/a1db3e77-9a41-4bad-b88b-a67e7f859ebb)

**Additional context**
 - Windows version: 10
 - Playnite version: 10.32
 - Link Utilities version: 4.0

**Comment by HerrKnarz** [comment]
The browser search function depends on the website having a proper search results page that can be reached with a URL in which the only variable part is the search term. Unfortunately, this is not the case for every site, even if LinkUtilities offers the "normal" search for this. With Co-Optimus, however, I seem to have simply overlooked the appropriate URL. I have now added it. It will be included in the next version.

I will also add a browser search column to the wiki page for the supported pages so that you can check this in future.
