### ISSUE TITLE
[Enhancement][Wikipedia Metadata] Wikipedia API : Language Selector

### ISSUE THREAD

**Issue by PietroR91** [HerrKnarz/Playnite-Extensions#85]
**Is your feature request related to a problem? Please describe.**
It would be useful to have the possibility to select the language of the Wikipedia API, in order to obtain the descriptions also in other ​​other languages.

**Describe the solution you'd like**
Change the type of _baseUrl (WikipediaApiCaller.cs) to be variable taking the first part of url that define the language from a ui config.

i.e:
Wikipedia Language: IT => _baseUrl = "https://it.wikipedia.org/w/rest.php/v1/";
Wikipedia Language: FR => _baseUrl = "https://fr.wikipedia.org/w/rest.php/v1/";

Thanks

**Comment by HerrKnarz** [comment]
Unfortunately it's not that simple. For the description alone that would work, but everything else like developer, genre, rating etc. would be much more complex, because the corresponding boxes are different for most languages. Language support was requested already in issue #78 - you'll find a more detailed response there. I'll keep this one open, so it's easily found.
